# Generated by Django 4.0.4 on 2022-07-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_userfollows_followed_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
