# Generated by Django 4.0.4 on 2022-06-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ticket_has_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='has_review',
            new_name='has_critique',
        ),
    ]
