# Generated by Django 4.0.4 on 2022-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_has_review_ticket_has_critique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critique',
            name='headline',
            field=models.CharField(max_length=2048, verbose_name='Titre'),
        ),
    ]
