# Generated by Django 4.0.4 on 2022-07-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_critique_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critique',
            name='body',
            field=models.TextField(blank=True, max_length=8192, verbose_name='Critique'),
        ),
        migrations.AlterField(
            model_name='critique',
            name='headline',
            field=models.CharField(max_length=128, verbose_name='Titre'),
        ),
    ]
