# Generated by Django 4.0.4 on 2022-07-12 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='suivi par'),
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
